name: test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  nargo:
    runs-on: ubuntu-latest

    steps:
      - name: Install noirup
        run: |
          curl -L https://raw.githubusercontent.com/noir-lang/noirup/main/install | bash
          export PATH=$PATH:$HOME/.nargo/bin

      - name: Install noir nightly
        run: noirup -n

      - name: Run tests
        run: nargo test